# Generated by Django 3.2.15 on 2022-09-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ('index',), 'verbose_name': 'Pokemon', 'verbose_name_plural': 'Pokemons'},
        ),
        migrations.AlterModelOptions(
            name='pokemonability',
            options={'ordering': ('index',), 'verbose_name': 'Pokemon Ability', 'verbose_name_plural': 'Pokemon Abilities'},
        ),
        migrations.AlterModelOptions(
            name='pokemonspecies',
            options={'ordering': ('index',)},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='base_experience',
            field=models.IntegerField(null=True),
        ),
    ]
